[admin]
localhost ansible_connection=local

[application]
app-server ansible_host=10.0.1.211

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/my-main-server.pem
ansible_python_interpreter=/usr/bin/python3